#!/usr/bin/env Rscript
# Name: 	Combiner
# Purpose: 	Concatenates the temporary file generated by the survey with the existing dataset. This portion of the script is
# 		written in R so that I could utilize the rbind() functionality that always aligns data by column name and fills in
#		any missing values with NA.
# Updated: 	2018/10/29 CC

# Load the necessary data.table package.
library(data.table)

# If loop function
# First, if the data file has more than three columns (arbitrary number) then combine the temporary file with the existing data.
# Second, if the data file has an empty first column name, then drop that column or else combine them like normal
if(ncol(fread("data_folder/data", sep= " ")) > 3) {
	if(fread("data_folder/data", sep = " ", header = FALSE)[1,1] == " ") {
		df1 <- fread("data_folder/data", header= TRUE, sep = ",", drop = 1)
		df2 <- fread("data_folder/temp_file", header = TRUE, sep = " ")
		write.csv(rbind(df1, df2, fill = TRUE), file = "data_folder/data")
	} else {
		df1 <- fread("data_folder/data", header= TRUE, sep = " ")
                df2 <- fread("data_folder/temp_file", header = TRUE, sep = " ")
                write.csv(rbind(df1, df2, fill = TRUE), file = "data_folder/data")
	}
}
